# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Main_Win import Ui_Main_Screen


class Ui_logIn_screen(object):
    def func(self):
        
        pass_path = "C:\\Users\\hadir\\Documents\\VSC - Projects\\Business Class Year 10B 💼\\python\\logIn_Details.txt"
        username_inputed = self.username_field.text()
        password_inputed = self.password_field.text()
        
        with open(pass_path,'r') as file:
                  for line in file:
                        usernames = line.split()[0]
                        passwords = line.split()[1]
        
        if (username_inputed == usernames) and (password_inputed == passwords):
            print("ACESS GRANTED!")
            
            self.window = QtWidgets.QDialog()
            self.ui = Ui_Main_Screen()
            self.ui.setupUi(self.window)
            self.window.show()
        else:
            print("ACESS DECLINED!")
            self.close() 
            #print(f"Your username is {username} and your password is {password}")
            
    def setupUi(self, logIn_screen):
        logIn_screen.setObjectName("logIn_screen")
        logIn_screen.resize(1247, 822)
        logIn_screen.setStyleSheet("background: rgb(94, 94, 94)")
        self.widget = QtWidgets.QWidget(logIn_screen)
        self.widget.setGeometry(QtCore.QRect(30, 30, 1181, 771))
        self.widget.setStyleSheet("background: rgb(113, 113, 113)")
        self.widget.setObjectName("widget")
        self.logIn_label = QtWidgets.QLabel(self.widget)
        self.logIn_label.setGeometry(QtCore.QRect(370, 30, 451, 131))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.logIn_label.setFont(font)
        self.logIn_label.setObjectName("logIn_label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(340, 230, 281, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(340, 370, 281, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.username_field = QtWidgets.QLineEdit(self.widget)
        self.username_field.setGeometry(QtCore.QRect(340, 280, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.username_field.setFont(font)
        self.username_field.setObjectName("username_field")
        self.password_field = QtWidgets.QLineEdit(self.widget)
        self.password_field.setGeometry(QtCore.QRect(340, 430, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.password_field.setFont(font)
        self.password_field.setObjectName("password_field")
        self.login_bttn = QtWidgets.QPushButton(self.widget, clicked = lambda: self.func())
        
        
        self.login_bttn.setGeometry(QtCore.QRect(440, 530, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.login_bttn.setFont(font)
        self.login_bttn.setObjectName("login_bttn")

        self.retranslateUi(logIn_screen)
        QtCore.QMetaObject.connectSlotsByName(logIn_screen)

    def retranslateUi(self, logIn_screen):
        _translate = QtCore.QCoreApplication.translate
        logIn_screen.setWindowTitle(_translate("logIn_screen", "Dialog"))
        self.logIn_label.setText(_translate("logIn_screen", "      LOG IN"))
        self.label_2.setText(_translate("logIn_screen", "username :"))
        self.label_3.setText(_translate("logIn_screen", "password :"))
        self.login_bttn.setText(_translate("logIn_screen", "LOG IN !"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    logIn_screen = QtWidgets.QDialog()
    ui = Ui_logIn_screen()
    ui.setupUi(logIn_screen)
    logIn_screen.show()
    sys.exit(app.exec_())
