# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from rich.panel import Panel
from rich import print
import requests
import json

from rich.traceback import install
install(show_locals=True)


class Ui_Main_Screen(object):
    def setupUi(self, Main_Screen):
        Main_Screen.setObjectName("Main_Screen")
        Main_Screen.resize(1313, 845)
        Main_Screen.setStyleSheet("background-color: rgb(94, 94, 94)")
        self.tabWidget = QtWidgets.QTabWidget(Main_Screen)
        self.tabWidget.setGeometry(QtCore.QRect(10, 120, 1281, 721))
        self.tabWidget.setStyleSheet("background-color: rgb(172, 172, 172)")
        self.tabWidget.setObjectName("tabWidget")
        self.dashboardtab = QtWidgets.QWidget()
        self.dashboardtab.setObjectName("dashboardtab")
        self.widget = QtWidgets.QWidget(self.dashboardtab)
        self.widget.setGeometry(QtCore.QRect(10, 10, 471, 321))
        self.widget.setStyleSheet("background-color: rgb(36, 36, 36)")
        self.widget.setObjectName("widget")
        self.calendar = QtWidgets.QCalendarWidget(self.widget)
        self.calendar.setGeometry(QtCore.QRect(10, 10, 451, 301))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(172, 172, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 172, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 172, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 172, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 172, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 172, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 172, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 172, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 172, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.calendar.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.calendar.setFont(font)
        self.calendar.setStyleSheet("background-color: rgb(172, 172, 172)")
        self.calendar.setGridVisible(True)
        self.calendar.setObjectName("calendar")
        self.todo = QtWidgets.QTextEdit(self.dashboardtab)
        self.todo.setGeometry(QtCore.QRect(10, 340, 701, 341))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.todo.setFont(font)
        self.todo.setStyleSheet("background-color: rgb(255, 76, 79)")
        self.todo.setFrameShape(QtWidgets.QFrame.Panel)
        self.todo.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.todo.setLineWidth(10)
        self.todo.setMidLineWidth(4)
        self.todo.setObjectName("todo")
        self.tabWidget.addTab(self.dashboardtab, "")
        self.markettab = QtWidgets.QWidget()
        self.markettab.setObjectName("markettab")
        self.market_header = QtWidgets.QWidget(self.markettab)
        self.market_header.setGeometry(QtCore.QRect(60, 20, 1081, 81))
        self.market_header.setStyleSheet("background-color: rgb(132, 132, 132);\n"
"border-radius: 20px 20px;")
        self.market_header.setObjectName("market_header")
        self.Market_header = QtWidgets.QLabel(self.market_header)
        self.Market_header.setGeometry(QtCore.QRect(120, 20, 871, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Market_header.setFont(font)
        self.Market_header.setObjectName("Market_header")
        self.weather_info = QtWidgets.QWidget(self.markettab)
        self.weather_info.setGeometry(QtCore.QRect(40, 160, 471, 511))
        self.weather_info.setStyleSheet("background-color: rgb(132, 132, 132);\n"
"border-radius: 20px 20px;")
        self.weather_info.setObjectName("weather_info")
        self.market_header_2 = QtWidgets.QWidget(self.weather_info)
        self.market_header_2.setGeometry(QtCore.QRect(-80, 20, 621, 81))
        self.market_header_2.setStyleSheet("background-color: rgb(132, 132, 132);\n"
"border-radius: 20px 20px;")
        self.market_header_2.setObjectName("market_header_2")
        self.label_2 = QtWidgets.QLabel(self.market_header_2)
        self.label_2.setGeometry(QtCore.QRect(100, 0, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.weather_api_info = QtWidgets.QLabel(self.weather_info)
        self.weather_api_info.setGeometry(QtCore.QRect(20, 70, 421, 371))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.weather_api_info.setFont(font)
        self.weather_api_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.weather_api_info.setObjectName("weather_api_info")
        self.market_info = QtWidgets.QWidget(self.markettab)
        self.market_info.setGeometry(QtCore.QRect(530, 160, 641, 511))
        self.market_info.setStyleSheet("background-color: rgb(132, 132, 132);\n"
"border-radius: 20px 20px;")
        self.market_info.setObjectName("market_info")
        self.label_3 = QtWidgets.QLabel(self.market_info)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.market_api_info = QtWidgets.QLabel(self.market_info)
        self.market_api_info.setGeometry(QtCore.QRect(10, 90, 591, 371))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.market_api_info.setFont(font)
        self.market_api_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.market_api_info.setObjectName("market_api_info")
        self.tabWidget.addTab(self.markettab, "")
        self.my_Finanaces = QtWidgets.QWidget()
        self.my_Finanaces.setObjectName("my_Finanaces")
        self.tabWidget.addTab(self.my_Finanaces, "")
        self.label = QtWidgets.QLabel(Main_Screen)
        self.label.setGeometry(QtCore.QRect(120, 30, 1051, 81))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(34)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Main_Screen)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Main_Screen)

    def retranslateUi(self, Main_Screen):
            
            #------------------------------------------------------------------------------------------
        
        all_symbols = ["RICE","WHEAT","CORN","COFFEE","RUBBER","COTTON"]
        all_base_currency = "AED"
        
        access_key_2 = "fd95o5yj28iz3ukff9no7o5bmqvii5nx3mjqdlcsktz5h4rf1v8o4hk76722"
        endpoint = 'latest'
        
        api_data = dict()
        
        for i in all_symbols:
            loop_output = requests.get('https://commodities-api.com/api/'+endpoint+'?access_key='+access_key_2+'&base='+all_base_currency+'&symbols='+i) 
            loop_currency = {loop_output.json()['data']['base']}
            loop_vege_rate = {loop_output.json()['data']['rates'][str(i)]}
            loop_vegetable = i
            loop_units = {loop_output.json()['data']['unit']}
            loop_date = {loop_output.json()['data']['date']}
        
            loop_output = f"{loop_vege_rate} per : {loop_units}" 
        
            api_data.update({i: loop_output}) 
        
        prnt_api_output = "{" + "\n".join("{!r}: {!r},".format(k, v) for k, v in api_data.items()) + "}"  
        
        market_output = prnt_api_output
                
        #------------------------------------------------------------------------------------------
        
        #------------------------------------------------------------------------------------------
        
        api_key = "0c4d43f1d3c12b565156847bb4db7717"
 
        # base_url variable to store url
        base_url = "http://api.openweathermap.org/data/2.5/weather?"
        
        city_name = "Sharjah"
        
        complete_url = base_url + "appid=" + api_key + "&q=" + city_name
        
        response = requests.get(complete_url)
        
        x = response.json()
        
        if x["cod"] != "404":
        
            y = x['main']
        
            current_temperature = y["temp"]
        
            current_pressure = y["pressure"]
        
            current_humidity = y["humidity"]
        
            z = x["weather"]
        
            weather_description = z[0]["description"]
        
            weather_info = f" Temperature (in kelvin unit) = {str(current_temperature)} \n atmospheric pressure (in hPa unit) =  {str(current_pressure)} \n humidity (in percentage) =  {str(current_humidity)} \n description =  {str(weather_description)}"

        #------------------------------------------------------------------------------------------
        
        _translate = QtCore.QCoreApplication.translate
        Main_Screen.setWindowTitle(_translate("Main_Screen", "Dialog"))
        self.todo.setHtml(_translate("Main_Screen", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cascadia Code SemiBold\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">TO - DO :<br /><br /></span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dashboardtab), _translate("Main_Screen", "DashBoard"))
        self.Market_header.setText(_translate("Main_Screen", "           📉          MARKET ANALYSIS            📈 "))
        self.label_2.setText(_translate("Main_Screen", "Weather : "))
        
        self.weather_api_info.setText(_translate("Main_Screen", f"{weather_info}"))
        
        self.label_3.setText(_translate("Main_Screen", "Market : "))
        
        self.market_api_info.setText(_translate("Main_Screen", f"{market_output}"))
        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.markettab), _translate("Main_Screen", "Market"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.my_Finanaces), _translate("Main_Screen", "My Finances"))
        self.label.setText(_translate("Main_Screen", "          🌾 AG ZONE  👨🏻‍🌾"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main_Screen = QtWidgets.QDialog()
    ui = Ui_Main_Screen()
    ui.setupUi(Main_Screen)
    Main_Screen.show()
    sys.exit(app.exec_())
